ci: Remove PHP 8.0
It should still work but PHPStan would get angry:

    Error: Property Nette\Forms\Rendering\DefaultFormRenderer::$form (Nette\Forms\Form) in isset() is not nullable.
    Error: Property Nette\Forms\Rendering\DefaultFormRenderer::$form (Nette\Forms\Form) in isset() is not nullable.
    Error: Parameter #1 $object_or_class of function method_exists expects object|string, mixed given.
    Error: Cannot call method getLabelPrototype() on class-string|object.
    Error: Property Nette\Forms\Rendering\DefaultFormRenderer::$form (Nette\Forms\Form) in isset() is not nullable.
    Error: Parameter #1 $object_or_class of function method_exists expects object|string, mixed given.
    Error: Cannot call method getControlPrototype() on class-string|object.
    Error: Cannot call method getControlPrototype() on class-string|object.
    Error: Cannot call method getLabelPrototype() on class-string|object.

Likely because on PHP 8.0 we need to use `nette/forms` 3.1.15 rather than 3.2.9 used by PHP 8.1, and the former uses PHPDoc instead of property type hints:

https://github.com/nette/forms/blob/v3.1.15/src/Forms/Rendering/DefaultFormRenderer.php#L121

And we do not want to bother fixing it.